### ISSUE TITLE
状况-can't get service

### ISSUE THREAD

**Issue by gujindv** [springjk/test-yunti-speed#9]
![image](https://cloud.githubusercontent.com/assets/23071138/20554483/402f6220-b197-11e6-8819-f58b7585c34f.png)
你好 请问出现这种状况怎么解决呢

**Comment by springjk** [comment]
你好,首先非常高兴你使用它 😄 。

前一段时间云梯频繁跟换域名，国内地址也无法直接访问，于是中断了这个的更新，这个错误其实是没法访问云梯的服务器，而且他们新开了 IKEV2 模式，加上新版 Mac 取消支持 PPTP，今晚我会做好兼容。

**Comment by gujindv** [comment]
谢谢你帮忙，我又重新装了，不过还是有这个问题，不知道怎么回事？
Note:在断开vpn和开着vpn的状态下， $ yunti,  都会得到以下提示。

⮀ yunti

ping 啊 ping，ping 个大气球…

name     type     ip     avg

延迟最低 L2TP 的线路为：云梯   AVG:

正在连接云梯  …
96:110: execution error: System Events got an error: Can’t get service "云梯  " of current location of network preferences. (-1728)

检测连接状态超时，请亲自确认 VPN 是否已连接。


--我的系统信息：
system:      "osx/10.11/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)"
    zsh:         "/bin/zsh => zsh 5.0.8 (x86_64-apple-darwin15.0)"

  rvm:
    version:      "rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "6 hours 36 minutes 17 seconds ago"
    path:         "/Users/wdl/.rvm"

**Comment by springjk** [comment]
这个我认为是之前的错误日志没有有被清除，害你当小白鼠了；

首先进入代码目录，如果你是全局安装模式不知道安装在那里，那么可以执行

`cd $(string=$(ll $(where yunti) | cut -d ">" -f2) && echo ${string:0:-5})` 

进入代码目录后 `ll` 可以看到两个 `txt` 文件，删除这两个文件 `rm *.txt` 应该即可恢复。

**Comment by springjk** [comment]
这个项目我已经用三台机器测试过，目前尚未发现问题，如果上述操作没有解决你的问题，你也可以更换一个目录安装进行测试。

另外，你也可以关注 [vpn-helper](https://github.com/springjk/vpn-helper)，这个将会是我主要更新的项目，`test-yunti-speed` 仅针对云梯，从云梯网站获取数据，如果云梯站点更新频繁必然会产生各类问题，`vpn-helper`针对所有 VPN，数据从用户机器上获取，另外我会将其作为 composer 包发布到 [packagist](https://packagist.org/packages/)，欢迎试用。

**Comment by gujindv** [comment]
优秀！多谢少侠！小白鼠当的不冤，再也不用一个个试云梯线路了。

**Comment by springjk** [comment]
fix by #10
